### ISSUE TITLE
A small todo-list for when I come back to this project

### ISSUE THREAD

**Issue by slumpsand** [slumpsand/nut#1]
- [ ] auto run the build task
- [ ] allow slashes in asset identifiers
- [ ] transfer git repository ownership
- [ ] don't refer Firefox in the `Open in Browser` task directly
- [ ] in some files tabs are eight wide, make that four
- [ ] there must be a way to debug web-applications
- [ ] find the problems hotkey (vscode)
- [ ] add the `data/` folder to the gitignore 
- [ ] remove the images from the git history
